spring.application.name=hrms
spring.datasource.url=jdbc:mysql://localhost:3306/hrms_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#to see SQL query
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
